---
title: Developing an R package for a research group
author: Emil Tveden Bjerglund
date: '2017-07-07'
slug: developing-an-r-package-for-a-research-group
categories: [R, Open Science]
tags: []
bibliography: ../lib.bib
csl: ../csl/american-chemical-society-with-titles-doi-no-et-al.csl

---

Currently in the Organic Surface Chemistry group there are large variations between group members when it comes to the tools used for data analysis. Some people feel most comfortable in spreadsheet programs such as Origin or Excel, while others rely on a mix of Matlab, R, Python or other tools. We use a lot of different experimental techniques in our research, and therefore generate data in a lot of different formats. Different workflows of varying efficiency often makes joint projects more difficult than necessary.

# Open Science
Recently a lot of our research activities has been oriented towards the [SPOMAN Open Science collaboration](//www.spoman-os.org), and the ongoing projects are available on the [Open Science Framework (osf.io)](//osf.io/wudyt). In most cases, the methods and results are thoroughly described for each project. However, since a lot of the data analysis is currently performed in spreadsheet software, the data analysis is not very transparent and reproducible. Our research could be made more efficient and well-documented if R was adopted as a general tool for data analysis.[@Lowndes2017]

* Very clear and well-documented data analysis by use of R Markdown documents, were descriptions scripts etc. can be made available in plain-text files.
* Reuse of code for common techniques by developing an R package containing methods that can be useful for all group members.

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```


# References
